PS D:\CMS\CMS> python main.py
Firm documents table columns after ALTER: ['id', 'work_id', 'firm_name', 'pg_no', 'pg_amount', 'bank_name', 'bank_address', 'firm_address', 'indemnity_bond_details', 'other_docs_details', 'submission_date', 'pg_submitted', 'indemnity_bond_submitted']
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python313\Lib\tkinter\__init__.py", line 2068, in __call__
    return self.func(*args)
           ~~~~~~~~~^^^^^^^
  File "D:\CMS\CMS\features\vitiation\QuantityVariationDialog.py", line 129, in save
    self.main_app_instance.reference_firm_var.set(firm_name)
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QuantityVariationDialog' object has no attribute 'main_app_instance'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python313\Lib\tkinter\__init__.py", line 2068, in __call__
    return self.func(*args)
           ~~~~~~~~~^^^^^^^
  File "D:\CMS\CMS\features\vitiation\QuantityVariationDialog.py", line 129, in save
    self.main_app_instance.reference_firm_var.set(firm_name)
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QuantityVariationDialog' object has no attribute 'main_app_instance'
PS D:\CMS\CMS> python main.py
Firm documents table columns after ALTER: ['id', 'work_id', 'firm_name', 'pg_no', 'pg_amount', 'bank_name', 'bank_address', 'firm_address', 'indemnity_bond_details', 'other_docs_details', 'submission_date', 'pg_submitted', 'indemnity_bond_submitted']
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python313\Lib\tkinter\__init__.py", line 2068, in __call__
    return self.func(*args)
           ~~~~~~~~~^^^^^^^
  File "D:\CMS\CMS\features\vitiation\QuantityVariationDialog.py", line 129, in save
    self.main_app_instance.reference_firm_var.set(firm_name)
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QuantityVariationDialog' object has no attribute 'main_app_instance'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python313\Lib\tkinter\__init__.py", line 2068, in __call__
    return self.func(*args)
           ~~~~~~~~~^^^^^^^
  File "D:\CMS\CMS\features\vitiation\QuantityVariationDialog.py", line 129, in save
    self.main_app_instance.reference_firm_var.set(firm_name)
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QuantityVariationDialog' object has no attribute 'main_app_instance'
PS D:\CMS\CMS> python main.py
Firm documents table columns after ALTER: ['id', 'work_id', 'firm_name', 'pg_no', 'pg_amount', 'bank_name', 'bank_address', 'firm_address', 'indemnity_bond_details', 'other_docs_details', 'submission_date', 'pg_submitted', 'indemnity_bond_submitted']
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python313\Lib\tkinter\__init__.py", line 2068, in __call__
    return self.func(*args)
           ~~~~~~~~~^^^^^^^
  File "D:\CMS\CMS\features\vitiation\QuantityVariationDialog.py", line 129, in save
    self.main_app_instance.reference_firm_var.set(firm_name)
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QuantityVariationDialog' object has no attribute 'main_app_instance'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python313\Lib\tkinter\__init__.py", line 2068, in __call__
    return self.func(*args)
           ~~~~~~~~~^^^^^^^
  File "D:\CMS\CMS\features\vitiation\QuantityVariationDialog.py", line 129, in save
    self.main_app_instance.reference_firm_var.set(firm_name)
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QuantityVariationDialog' object has no attribute 'main_app_instance'
